
#official python image
FROM python:3.9-slim 

#set wokring directory
WORKDIR /app

#copy the current directory contents into the container at /app
COPY . /app


#Install any needed packages specified in the requirements.txt
RUN pip install flask


#make port 5000 available to the world outside this container
EXPOSE 5000


#Run app.py whne the container launches
CMD [ "python", "app.py" ]



